# train_drt_baseline_paper.py
"""Train DRT baseline with the DRT-Net paper data protocol and settings.

Paper protocol used here:
- HR-MSI is generated by uniformly selecting five bands from the reference HSI.
- LR-HSI is generated by 5x5 Gaussian blur with sigma=2 followed by 4x downsampling.
- The center 128x128 subregion is used for testing.
- Training crops are 128x128; pixels overlapping the center test region are zeroed.
- Training uses Adam, lr=1e-4, and 10000 epochs by default.

The model remains the no-innovation DRT baseline: no rectangular transformer,
no SAFA multiscale adaptive aggregation, and no contrastive learning.
"""

from __future__ import annotations

import argparse
import os
import random
from dataclasses import dataclass
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset

from config import get_dataset_configs, print_config
from data_loader import (
    crop_to_scale,
    gaussian_blur_bandwise,
    hsi_to_tensor,
    normalize_hsi,
    read_hsi_mat,
    resize_hsi,
)
from metrics import MetricAverager, calc_metrics
from models import build_drt_baseline
from utils import (
    CSVLogger,
    count_parameters,
    get_device,
    load_checkpoint,
    move_to_device,
    save_checkpoint,
    set_seed,
    write_log,
)


@dataclass
class PaperConfig:
    stage: str = "train"
    dataset: str = "PaviaU"
    data_root: str = "./data/raw"
    checkpoint_root: str = "./checkpoints"
    log_root: str = "./logs"
    output_root: str = "./outputs"

    image_size: int = 128
    patch_size: int = 128
    scale_ratio: int = 4
    n_select_bands: int = 5
    gaussian_kernel: int = 5
    gaussian_sigma: float = 2.0
    train_patches_per_epoch: int = 512

    epochs: int = 10000
    batch_size: int = 1
    num_workers: int = 0
    lr: float = 1e-4
    weight_decay: float = 0.0
    seed: int = 10
    device: str = "cuda"

    hidden_dim: int = 48
    depth: int = 2
    heads: int = 4
    dropout: float = 0.0

    lambda_mse: float = 1.0
    lambda_spe: float = 1.0
    score_sam_weight: float = 1.0
    grad_clip: float = 1.0

    save_interval: int = 50
    eval_interval: int = 1
    resume: str = ""
    save_name: str = ""

    datasets: dict | None = None


def parse_args() -> PaperConfig:
    parser = argparse.ArgumentParser(description="DRT baseline with DRT-Net paper protocol")
    parser.add_argument("--stage", type=str, default="train")
    parser.add_argument("--dataset", type=str, default="PaviaU")
    parser.add_argument("--data_root", type=str, default="./data/raw")
    parser.add_argument("--checkpoint_root", type=str, default="./checkpoints")
    parser.add_argument("--log_root", type=str, default="./logs")
    parser.add_argument("--output_root", type=str, default="./outputs")

    parser.add_argument("--image_size", type=int, default=128)
    parser.add_argument("--patch_size", type=int, default=128)
    parser.add_argument("--scale_ratio", type=int, default=4)
    parser.add_argument("--n_select_bands", type=int, default=5)
    parser.add_argument("--gaussian_kernel", type=int, default=5)
    parser.add_argument("--gaussian_sigma", type=float, default=2.0)
    parser.add_argument("--train_patches_per_epoch", type=int, default=512)

    parser.add_argument("--epochs", type=int, default=10000)
    parser.add_argument("--batch_size", type=int, default=1)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=0.0)
    parser.add_argument("--seed", type=int, default=10)
    parser.add_argument("--device", type=str, default="cuda")

    parser.add_argument("--hidden_dim", type=int, default=48)
    parser.add_argument("--depth", type=int, default=2)
    parser.add_argument("--heads", type=int, default=4)
    parser.add_argument("--dropout", type=float, default=0.0)

    parser.add_argument("--lambda_mse", type=float, default=1.0)
    parser.add_argument("--lambda_spe", type=float, default=1.0)
    parser.add_argument("--score_sam_weight", type=float, default=1.0)
    parser.add_argument("--grad_clip", type=float, default=1.0)

    parser.add_argument("--save_interval", type=int, default=50)
    parser.add_argument("--eval_interval", type=int, default=1)
    parser.add_argument("--resume", type=str, default="")
    parser.add_argument("--save_name", type=str, default="")

    args = parser.parse_args()
    cfg = PaperConfig()
    cfg.datasets = get_dataset_configs()
    for key, value in vars(args).items():
        setattr(cfg, key, value)

    os.makedirs(cfg.checkpoint_root, exist_ok=True)
    os.makedirs(cfg.log_root, exist_ok=True)
    os.makedirs(cfg.output_root, exist_ok=True)
    return cfg


def center_rect(h: int, w: int, size: int) -> Tuple[int, int, int, int]:
    top = max((h - size) // 2, 0)
    left = max((w - size) // 2, 0)
    return top, left, top + size, left + size


def uniform_select_msi(hr_hsi: np.ndarray, n_select_bands: int) -> np.ndarray:
    """Match the DRTNet code-style uniform MSI selection: first, middle gap bands, last."""
    n_bands = hr_hsi.shape[2]
    if n_select_bands < 2:
        raise ValueError("n_select_bands must be at least 2 for paper-style uniform selection.")
    if n_select_bands > n_bands:
        raise ValueError(f"n_select_bands={n_select_bands} > n_bands={n_bands}")

    gap = n_bands / (n_select_bands - 1.0)
    indices = [0]
    for i in range(1, n_select_bands - 1):
        indices.append(min(int(gap * i), n_bands - 1))
    indices.append(n_bands - 1)
    return hr_hsi[:, :, indices].astype(np.float32)


def make_lr_hsi_paper(hr_hsi: np.ndarray, scale_ratio: int, kernel_size: int, sigma: float) -> np.ndarray:
    h, w, _ = hr_hsi.shape
    blurred = gaussian_blur_bandwise(hr_hsi, kernel_size=kernel_size, sigma=sigma)
    return resize_hsi(blurred, h // scale_ratio, w // scale_ratio).astype(np.float32)


def zero_test_overlap(patch: np.ndarray, patch_top: int, patch_left: int, test_rect: Tuple[int, int, int, int]) -> np.ndarray:
    t, l, b, r = test_rect
    pt, pl = patch_top, patch_left
    pb, pr = patch_top + patch.shape[0], patch_left + patch.shape[1]

    it = max(t, pt)
    il = max(l, pl)
    ib = min(b, pb)
    ir = min(r, pr)
    if it >= ib or il >= ir:
        return patch

    out = patch.copy()
    out[it - pt:ib - pt, il - pl:ir - pl, :] = 0.0
    return out


class PaperWaldDataset(Dataset):
    def __init__(self, img: np.ndarray, cfg: PaperConfig, split: str):
        super().__init__()
        self.img = img
        self.cfg = cfg
        self.split = split
        h, w, _ = img.shape
        self.test_rect = center_rect(h, w, cfg.image_size)

        if split == "test":
            self.coords = [(self.test_rect[0], self.test_rect[1])]
        else:
            self.coords = None

    def __len__(self) -> int:
        if self.split == "test":
            return 1
        return self.cfg.train_patches_per_epoch

    def _random_train_coord(self) -> Tuple[int, int]:
        h, w, _ = self.img.shape
        max_top = h - self.cfg.patch_size
        max_left = w - self.cfg.patch_size
        if max_top < 0 or max_left < 0:
            raise ValueError(f"Image {self.img.shape} is smaller than patch_size={self.cfg.patch_size}")
        return random.randint(0, max_top), random.randint(0, max_left)

    def __getitem__(self, index: int) -> Dict[str, torch.Tensor]:
        if self.split == "test":
            top, left = self.coords[0]
            size = self.cfg.image_size
            gt = self.img[top:top + size, left:left + size, :].copy()
        else:
            top, left = self._random_train_coord()
            size = self.cfg.patch_size
            gt = self.img[top:top + size, left:left + size, :].copy()
            gt = zero_test_overlap(gt, top, left, self.test_rect)

        lr_hsi = make_lr_hsi_paper(
            gt,
            scale_ratio=self.cfg.scale_ratio,
            kernel_size=self.cfg.gaussian_kernel,
            sigma=self.cfg.gaussian_sigma,
        )
        hr_msi = uniform_select_msi(gt, self.cfg.n_select_bands)

        return {
            "lr_hsi": hsi_to_tensor(lr_hsi),
            "hr_msi": hsi_to_tensor(hr_msi),
            "gt": hsi_to_tensor(gt),
            "dataset_id": torch.tensor(0, dtype=torch.long),
            "n_bands": torch.tensor(gt.shape[2], dtype=torch.long),
        }


class DRTPaperLoss(nn.Module):
    def __init__(self, lambda_mse: float = 1.0, lambda_spe: float = 1.0):
        super().__init__()
        self.lambda_mse = lambda_mse
        self.lambda_spe = lambda_spe

    def forward(self, pred: torch.Tensor, gt: torch.Tensor, model: nn.Module):
        loss_mse = 0.5 * F.mse_loss(pred, gt)
        pred_spe = model.spectral_reconstruction(pred)
        loss_spe = 0.5 * F.mse_loss(pred_spe, pred)
        loss_contrast = pred.new_tensor(0.0)
        loss = self.lambda_mse * loss_mse + self.lambda_spe * loss_spe + loss_contrast
        return loss, {
            "loss": loss.detach(),
            "mse": loss_mse.detach(),
            "spe": loss_spe.detach(),
            "contrast": loss_contrast.detach(),
        }


def build_paper_loaders(cfg: PaperConfig):
    dataset_cfg = cfg.datasets[cfg.dataset]
    file_path = os.path.join(cfg.data_root, dataset_cfg.file_name)
    img = read_hsi_mat(file_path, dataset_cfg.mat_keys)
    img = normalize_hsi(img)
    img = crop_to_scale(img, cfg.scale_ratio)

    train_set = PaperWaldDataset(img, cfg, split="train")
    test_set = PaperWaldDataset(img, cfg, split="test")

    train_loader = DataLoader(
        train_set,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    test_loader = DataLoader(
        test_set,
        batch_size=1,
        shuffle=False,
        num_workers=0,
        pin_memory=torch.cuda.is_available(),
    )

    info = {
        "dataset": cfg.dataset,
        "n_bands": img.shape[2],
        "n_select_bands": cfg.n_select_bands,
        "scale_ratio": cfg.scale_ratio,
        "test_rect": train_set.test_rect,
        "msi_generation": "uniform_select_5_bands",
        "lr_generation": f"gaussian_{cfg.gaussian_kernel}x{cfg.gaussian_kernel}_sigma_{cfg.gaussian_sigma}_downsample_x{cfg.scale_ratio}",
        "normalization": "minmax_0_1",
    }
    return train_loader, test_loader, info


def calc_checkpoint_score(eval_metrics, cfg):
    psnr = float(eval_metrics.get("PSNR", -1.0))
    sam = float(eval_metrics.get("SAM", 1e6))
    return psnr - float(cfg.score_sam_weight) * sam


def train_one_epoch(model, loader, optimizer, criterion, cfg, device):
    model.train()
    meter = MetricAverager()
    total_loss = 0.0
    for batch in loader:
        batch = move_to_device(batch, device)
        lr_hsi = batch["lr_hsi"]
        hr_msi = batch["hr_msi"]
        gt = batch["gt"]

        optimizer.zero_grad(set_to_none=True)
        pred = model(lr_hsi, hr_msi)
        loss, loss_dict = criterion(pred, gt, model)
        loss.backward()
        if cfg.grad_clip > 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), cfg.grad_clip)
        optimizer.step()

        total_loss += float(loss.item())
        meter.update({k: float(v.item()) for k, v in loss_dict.items()})

    avg = meter.average()
    avg["train_loss_total"] = total_loss / max(len(loader), 1)
    avg["w_mse"] = cfg.lambda_mse
    avg["w_spe"] = cfg.lambda_spe
    return avg


@torch.no_grad()
def evaluate(model, loader, cfg, device):
    model.eval()
    meter = MetricAverager()
    for batch in loader:
        batch = move_to_device(batch, device)
        pred = model(batch["lr_hsi"], batch["hr_msi"])
        pred = torch.clamp(pred, 0.0, 1.0)
        meter.update(calc_metrics(pred, batch["gt"], cfg.scale_ratio))
    return meter.average()


def main():
    cfg = parse_args()
    print_config(cfg)
    set_seed(cfg.seed)
    device = get_device(cfg.device)

    train_loader, test_loader, info = build_paper_loaders(cfg)
    model = build_drt_baseline(
        n_bands=info["n_bands"],
        n_msi_bands=info["n_select_bands"],
        scale_ratio=cfg.scale_ratio,
        hidden_dim=cfg.hidden_dim,
        depth=cfg.depth,
        heads=cfg.heads,
        dropout=cfg.dropout,
        srf_weights=None,
    ).to(device)

    criterion = DRTPaperLoss(lambda_mse=cfg.lambda_mse, lambda_spe=cfg.lambda_spe).to(device)
    optimizer = Adam(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

    save_name = cfg.save_name or f"{cfg.dataset}_drt_baseline_paper_protocol.pth"
    ckpt_dir = os.path.join(cfg.checkpoint_root, "drt_baseline_paper")
    ckpt_path = os.path.join(ckpt_dir, save_name)
    best_path = os.path.join(ckpt_dir, save_name.replace(".pth", "_best.pth"))
    log_path = os.path.join(cfg.log_root, f"{cfg.dataset}_drt_baseline_paper.log")
    csv_path = os.path.join(cfg.log_root, f"{cfg.dataset}_drt_baseline_paper.csv")

    start_epoch = 1
    best_score = -1e9
    best_psnr = -1.0
    best_sam = 1e9
    if cfg.resume:
        start_epoch, best_score = load_checkpoint(
            model,
            cfg.resume,
            optimizer=optimizer,
            strict=False,
            map_location=str(device),
            load_optimizer=True,
        )
        start_epoch += 1

    write_log(log_path, f"Model parameters: {count_parameters(model):.3f} M")
    write_log(log_path, f"Dataset info: {info}")
    write_log(log_path, "Paper protocol: HR-MSI uniform five-band selection; LR-HSI Gaussian 5x5 sigma=2 then 4x downsample.")
    write_log(log_path, "Paper split: center 128x128 test crop; training crop overlap with test region is zeroed.")
    write_log(log_path, "Paper training defaults: Adam optimizer, lr=0.0001, epochs=10000.")
    write_log(log_path, "Loss: Lmse + Lspe + Lc, with Lc=0 because this baseline removes contrastive learning.")

    csv_logger = CSVLogger(
        csv_path,
        fieldnames=[
            "epoch", "train_loss_total", "loss", "mse", "spe", "contrast", "w_mse", "w_spe",
            "PSNR", "RMSE", "SAM", "ERGAS", "SSIM", "CC",
            "checkpoint_score", "best_score", "best_psnr", "best_sam",
        ],
    )

    for epoch in range(start_epoch, cfg.epochs + 1):
        train_metrics = train_one_epoch(model, train_loader, optimizer, criterion, cfg, device)
        eval_metrics = {}
        checkpoint_score = ""

        if epoch % cfg.eval_interval == 0:
            eval_metrics = evaluate(model, test_loader, cfg, device)
            checkpoint_score = calc_checkpoint_score(eval_metrics, cfg)
            psnr = eval_metrics.get("PSNR", -1.0)
            sam = eval_metrics.get("SAM", 1e9)
            if checkpoint_score > best_score:
                best_score = checkpoint_score
                best_psnr = psnr
                best_sam = sam
                save_checkpoint(
                    model,
                    optimizer,
                    epoch,
                    best_score,
                    best_path,
                    extra={
                        "cfg": cfg.__dict__,
                        "info": info,
                        "best_score": best_score,
                        "best_psnr": best_psnr,
                        "best_sam": best_sam,
                        "score_formula": f"PSNR - {cfg.score_sam_weight} * SAM",
                        "protocol": "DRT-Net paper Wald protocol; uniform 5-band MSI; Gaussian blur/downsample LR-HSI",
                    },
                )

        if epoch % cfg.save_interval == 0:
            save_checkpoint(
                model,
                optimizer,
                epoch,
                best_score,
                ckpt_path,
                extra={
                    "cfg": cfg.__dict__,
                    "info": info,
                    "best_score": best_score,
                    "best_psnr": best_psnr,
                    "best_sam": best_sam,
                    "score_formula": f"PSNR - {cfg.score_sam_weight} * SAM",
                    "protocol": "DRT-Net paper Wald protocol; uniform 5-band MSI; Gaussian blur/downsample LR-HSI",
                },
            )

        msg = f"Epoch {epoch:04d}/{cfg.epochs} | train_loss={train_metrics['train_loss_total']:.6f}"
        msg += f" | mse={train_metrics.get('mse', 0.0):.6f} spe={train_metrics.get('spe', 0.0):.6f}"
        if eval_metrics:
            msg += (
                f" | PSNR={eval_metrics['PSNR']:.4f} RMSE={eval_metrics['RMSE']:.6f} "
                f"SAM={eval_metrics['SAM']:.4f} ERGAS={eval_metrics['ERGAS']:.4f} "
                f"SSIM={eval_metrics['SSIM']:.4f} CC={eval_metrics['CC']:.4f} "
                f"score={checkpoint_score:.4f} best_score={best_score:.4f} "
                f"best_psnr={best_psnr:.4f} best_sam={best_sam:.4f}"
            )
        write_log(log_path, msg)

        row = {
            "epoch": epoch,
            **train_metrics,
            **eval_metrics,
            "checkpoint_score": checkpoint_score,
            "best_score": best_score,
            "best_psnr": best_psnr,
            "best_sam": best_sam,
        }
        csv_logger.write(row)

    save_checkpoint(
        model,
        optimizer,
        cfg.epochs,
        best_score,
        ckpt_path,
        extra={
            "cfg": cfg.__dict__,
            "info": info,
            "best_score": best_score,
            "best_psnr": best_psnr,
            "best_sam": best_sam,
            "score_formula": f"PSNR - {cfg.score_sam_weight} * SAM",
            "protocol": "DRT-Net paper Wald protocol; uniform 5-band MSI; Gaussian blur/downsample LR-HSI",
        },
    )
    write_log(log_path, f"Training finished. Best score={best_score:.4f}, best PSNR={best_psnr:.4f}, best SAM={best_sam:.4f}. Best checkpoint: {best_path}")


if __name__ == "__main__":
    main()
